[project]
name = "pivma"
version = "0.1.0"
description = ""
authors = [
    {name = "meirelesgc",email = "geu_costa@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
]

[tool.poetry]
packages = [{include = "pivma", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
